sample/Ardalis.Result.SampleWeb.FunctionalTests/Ardalis.Result.SampleWeb.FunctionalTests.csproj, sample/Ardalis.Result.SampleWeb/Ardalis.Result.SampleWeb.csproj, sample/Ardalis.Result.SampleWeb/Pages/Index.cshtml, sample/Ardalis.Result.SampleWeb/Pages/Index.cshtml.cs, sample/Ardalis.Result.SampleWeb/Startup.cs
=> Adding razor pages with instructions to sample

sample/Ardalis.Result.SampleWeb.FunctionalTests/WeatherForecastControllerPost.cs, sample/Ardalis.Result.SampleWeb/Ardalis.Result.SampleWeb.csproj, sample/Ardalis.Result.SampleWeb/WeatherForecastFeature/ForecastEndpoint.cs, sample/Ardalis.Result.SampleWeb/WeatherForecastFeature/WeatherForecastController.cs, src/Ardalis.Result.AspNetCore/Ardalis.Result.AspNetCore.csproj
=> Add Endpoint and Tests

src/Ardalis.Result/Ardalis.Result.csproj, src/Ardalis.Result/Result.cs, tests/Ardalis.Result.UnitTests/ResultConstructor.cs, tests/Ardalis.Result.UnitTests/ResultImplicitOperators.cs
Fixes #25 
I hope you won't mind my jumping on this issue when it is not assigned to me, but it was a relatively quick and easy one to do while awaiting feedback on the other FluentValidation issue.
=> #25 Added implicit type converters to and from T Value and Success Result<T>

sample/Ardalis.Result.SampleWeb/Ardalis.Result.SampleWeb.csproj, sample/Ardalis.Sample.Core/WeatherService.cs, src/Ardalis.Result.AspNetCore/Ardalis.Result.AspNetCore.csproj, src/Ardalis.Result.AspNetCore/ResultExtensions.cs, src/Ardalis.Result.AspNetCore/TranslateResultToActionResultAttribute.cs, src/Ardalis.Result/Ardalis.Result.csproj, src/Ardalis.Result/IResult.cs, src/Ardalis.Result/Result.cs, tests/Ardalis.Result.UnitTests/ResultConstructor.cs
=> IResult.ValidationErrors be Dictionary<string, string[]> to allow multiple errors for the same key

sample/Ardalis.Result.SampleWeb/MapResultToActionResultAttribute.cs, sample/Ardalis.Result.SampleWeb/Program.cs, sample/Ardalis.Result.SampleWeb/Startup.cs, sample/Ardalis.Sample.Core/Ardalis.Sample.Core.csproj, src/Ardalis.Result.AspNetCore/Ardalis.Result.AspNetCore.csproj, src/Ardalis.Result.AspNetCore/ResultExtensions.cs, src/Ardalis.Result.AspNetCore/TranslateResultToActionResultAttribute.cs, src/Ardalis.Result/Ardalis.Result.csproj, tests/Ardalis.Result.UnitTests/Ardalis.Result.UnitTests.csproj
- Clear using.
- Change versions and packages reference.
=> Change versions and packages reference

README.md
- Added code example to README.md.
- Added Ardalis.Result.FluentValidation link to README.md.
=> Added code example to README.md

src/Ardalis.Result/Ardalis.Result.csproj, src/Ardalis.Result/Result.cs
=> Added setter to ValueType.

sample/Ardalis.Result.Sample.Core/Services/WeatherService.cs, sample/Ardalis.Result.SampleWeb/Ardalis.Result.SampleWeb.csproj, sample/Ardalis.Result.SampleWeb/MediatrApi/LoggingBehavior.cs, sample/Ardalis.Result.SampleWeb/MediatrApi/WeatherForecastController.cs, sample/Ardalis.Result.SampleWeb/Startup.cs
Researching if we can do Result translation in sample; nope.
Fixes #7
=> MediatR Pipeline in Sample

src/Ardalis.Result/Result.cs, tests/Ardalis.Result.UnitTests/ResultImplicitOperators.cs
=> Success with message added.

src/Ardalis.Result/PagedInfo.cs, src/Ardalis.Result/PagedResult.cs, src/Ardalis.Result/Result.cs, tests/Ardalis.Result.UnitTests/PagedResultConstructor.cs, tests/Ardalis.Result.UnitTests/PagedResultImplicitOperators.cs
=> Shady nagy/paged result

src/Ardalis.Result/Result.cs, tests/Ardalis.Result.UnitTests/ResultConstructor.cs
=> Added IsSuccess property to Result

src/Ardalis.Result/Ardalis.Result.csproj, src/Ardalis.Result/Result.cs
Adding Unauthorized result
Adding XML comments
=> Publishing Version 3.1.2

src/Ardalis.Result.FluentValidation/FluentValidationResultExtensions.cs, src/Ardalis.Result/ValidationError.cs
Support of FluentValidation's ErrorCode property of ValidationResult in ValidationError class.
=> Support FluentValidation ErrorCode

README.md
Adds links to the project's README with relevant NimblePros and Ardalis blog content related to the Ardalis.Result package
=> Add relevant blog posts to README

src/Ardalis.Result/ResultExtensions.cs, tests/Ardalis.Result.UnitTests/ResultMap.cs
=> Map NotFound Errors

src/Ardalis.Result/Result.Void.cs, src/Ardalis.Result/Result.cs, tests/Ardalis.Result.UnitTests/ResultVoidConstructor.cs
Added CorrelationId property, ErrorWithCorrelationId() factory method and unit test
=> Added CorrelationId property to Result (#120)

sample/Ardalis.Result.SampleWeb/Pages/Index.cshtml
Add info on how to receive a conflict response to landing page
=> add conflict info to landing page

sample/Ardalis.Result.SampleWeb.FunctionalTests/PersonControllerCreate.cs, src/Ardalis.Result.AspNetCore/Ardalis.Result.AspNetCore.csproj, src/Ardalis.Result.FluentValidation/Ardalis.Result.FluentValidation.csproj, src/Ardalis.Result/Ardalis.Result.csproj
- Updates Version and PackageReleaseNotes
=> Bump Version to 7.1.0

src/Ardalis.Result.AspNetCore/Ardalis.Result.AspNetCore.csproj, src/Ardalis.Result.FluentValidation/Ardalis.Result.FluentValidation.csproj, src/Ardalis.Result/Ardalis.Result.csproj
=> Drop aspnetcore 2.2 dependencies

sample/Directory.Build.props, src/Directory.Build.props, tests/Directory.Build.props
- Adds `net8.0` to collection of .NET frameworks 
Closes #156
=> Add .NET 8 to NetCoreFrameworks 

src/Ardalis.Result/Result.cs, src/Ardalis.Result/ResultExtensions.cs, src/Ardalis.Result/ResultStatus.cs, tests/Ardalis.Result.UnitTests/ResultConstructor.cs, tests/Ardalis.Result.UnitTests/ResultMap.cs
add methods for created result
=> Add Created.Result

src/Ardalis.Result/IResultExtensions.cs, tests/Ardalis.Result.UnitTests/IResultExtensions.cs
=> ✨ 176 result status helpers
