ardalis/Result

sample/Ardalis.Result.SampleWeb/Extensions/ResultExtensions.cs
sample/Ardalis.Result.SampleWeb/MyResultActionFilter.cs
sample/Ardalis.Result.SampleWeb/WeatherForecastFeature/WeatherForecastController.cs
src/Ardalis.Result/Result.cs

An extension method added for ControllerBase which takes a Result<T>
and converts that to ActionResult<T>.
@ardalis , I am afraid we cannot use `ActionFilter` since the `Result` property in the context of all filters is of type `IActionResult` so we are losing the `T` type. If you found any other solutions except the extension method over controller I will be more than happy to hear about that too. 
I was also thinking about inheritance over conversion, but in that case, the library won't be general as it requires to reference some asp.net core libs. and it won't have access to the `ModelState` of the controller too.

chore: add extension method over ControllerBase

---

sample/Ardalis.Result.Sample.UnitTests/Ardalis.Result.Sample.UnitTests.csproj
tests/Ardalis.Result.UnitTests/Ardalis.Result.UnitTests.csproj

build workflow fails to find netcoreapp3.1 but net5.0 is present.
possbile fixes:
* use net5.0
* install net core hosting bundle

use net50 instead of netcoreapp3.1 in test projects

---

src/Ardalis.Result.FluentValidation/Ardalis.Result.FluentValidation.csproj

PR 1 of 2 to resolve https://github.com/ardalis/Result/issues/61
This resolves dependency issues with FluentValidation 10.x by only supporting 7.x to 9.x. 7.x is when Fluent validation switched to .NET Standard.

Updated FluentValidation version to the range that is actually supported

---

src/Ardalis.Result.FluentValidation/Ardalis.Result.FluentValidation.csproj

PR 2 of 2 for https://github.com/ardalis/Result/issues/61. [PR 1](https://github.com/ardalis/Result/pull/63) should be merged in first.
FluentValidation 10.x had a breaking change that impacted Ardalis.Result.FluentValidation. This enforces a minimum version of 10.x for FluentValidation.

Updated FluentValidation dependency to support the latest 10.x version

---

src/Ardalis.Result.AspNetCore/ResultExtensions.cs
src/Ardalis.Result.AspNetCore/TranslateResultToActionResultAttribute.cs

Adding of new statuses may require changes in multiple places.
But if we will reuse ToActionResult in TranslateResultToActionResultAttribute
we will minimize places that should be modified just in case of new ResultStatus.

reuse ToActionResult in TranslateResultToActionResultAttribute

---

sample/Ardalis.Result.Sample.Core/Services/PersonService.cs
sample/Ardalis.Result.SampleWeb.FunctionalTests/PersonControllerDelete.cs
src/Ardalis.Result.AspNetCore/ResultExtensions.cs
src/Ardalis.Result/Result.Void.cs
src/Ardalis.Result/Result.cs
tests/Ardalis.Result.UnitTests/ResultConstructor.cs

#95 
Replicated most of the behavior of `.Error()` but also made it so that if no string is provided it continues to use the standard 404 with no body.

Add the ability to return an error body with the Result.NotFound() extension

---

.github/workflows/comment-on-pr.yml
.github/workflows/dotnetcore.yml

- Moving the PR comment to a `workflow_run` workflow that is designed for having write access, based on guidance from [GitHub Security Lab: Keeping your GitHub Actions and workflows secure Part 1](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Closes #123

Working through code coverage from forks

---

src/Ardalis.Result.AspNetCore/Ardalis.Result.AspNetCore.csproj
src/Ardalis.Result.FluentValidation/Ardalis.Result.FluentValidation.csproj
src/Ardalis.Result/Ardalis.Result.csproj
src/Directory.Build.props

I broke the build with my last change because the CI process for publishing nuget packages expects the <Version> tag [to be in the csproj file](https://github.com/ardalis/Result/actions/runs/4756332307/jobs/8451728258#step:6:16). This change moves it back to the right spot.
I also noticed the publish action that's being used is [no longer maintained by the author](https://github.com/brandedoutcast/publish-nuget) and that it's using `set-output` which is deprecated and will start [failing bulids in June](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) (when Github officially gets rid of it).

Moved nuget version back into csproj to fix package publishing issues

---

.github/workflows/dotnetcore.yml
.github/workflows/publish-result-related.yml
.github/workflows/publish-result.yml

I noticed that there are [deprecation warnings](https://github.com/ardalis/Result/actions/runs/4757010978) with some of the action workflows. Additionally, the action that's being used to publish the nuget packages is [no longer maintained](https://github.com/brandedoutcast/publish-nuget#this-repository-is-archived-). This is a problem because that action uses the `set-output` command, which GitHub has deprecated and will be completely removing at the end of May.
These upgrades should clear warnings around a deprecated nodejs version and issuse with using `set-output`.
For the nuget package publishing, I haven't really been able to test the `push` command but I did try to replicate what the old action was doing to publish packages.

Updated github actions to remove deprecation warnings

---

.github/workflows/publish-result-related.yml
.github/workflows/publish-result.yml

Forgot this argument, so the pack command was trying to pack [debug assemblies](https://github.com/ardalis/Result/actions/runs/4757923748/jobs/8455342230#step:6:10). This should probably be it for me an PRs on this repo today 😅
To make sure this actually works, I did this locally:
```bash
dotnet clean
dotnet build --configuration Release
dotnet pack --no-build src/Ardalis.Result/Ardalis.Result.csproj --configuration Release --output nuget
dotnet pack --no-build src/Ardalis.Result.FluentValidation/Ardalis.Result.FluentValidation.csproj --configuration Release --output nuget
dotnet pack --no-build src/Ardalis.Result.AspNetCore/Ardalis.Result.AspNetCore.csproj --configuration Release --output nuget
```
and all the pack commands succeeded. apologies for all the CI noise.

Publish the release version of the nuget packages

---

sample/Ardalis.Result.Sample.Core/DTOs/CreatePersonRequestDto.cs
sample/Ardalis.Result.Sample.Core/Exceptions/ForecastConflictException.cs
sample/Ardalis.Result.Sample.Core/Services/PersonService.cs
sample/Ardalis.Result.Sample.Core/Services/WeatherService.cs
sample/Ardalis.Result.Sample.Core/Services/WeatherServiceWithExceptions.cs
sample/Ardalis.Result.Sample.UnitTests/ServiceTests/PersonServiceCreate.cs
sample/Ardalis.Result.SampleMinimalApi.FunctionalTests/NewWeatherForecast.cs
sample/Ardalis.Result.SampleWeb.FunctionalTests/PersonControllerCreate.cs
sample/Ardalis.Result.SampleWeb.FunctionalTests/PersonControllerDelete.cs
sample/Ardalis.Result.SampleWeb.FunctionalTests/WeatherForecastControllerPost.cs
sample/Ardalis.Result.SampleWeb/BadApproaches/BadWeatherForecastController.cs
sample/Ardalis.Result.SampleWeb/MediatrApi/PersonController.cs
sample/Ardalis.Result.SampleWeb/PersonFeature/CreatePersonEndpoint.cs
sample/Ardalis.Result.SampleWeb/PersonFeature/PersonController.cs
src/Ardalis.Result.AspNetCore/MinimalApiResultExtensions.cs
src/Ardalis.Result.AspNetCore/ResultStatusMap.cs
src/Ardalis.Result/Result.Void.cs
src/Ardalis.Result/Result.cs
src/Ardalis.Result/ResultExtensions.cs
src/Ardalis.Result/ResultStatus.cs
tests/Ardalis.Result.AspNetCore.UnitTests/ResultConventionDefaultResultStatusMap.cs
tests/Ardalis.Result.AspNetCore.UnitTests/ResultConventionDefaultResultStatusMapModified.cs
tests/Ardalis.Result.UnitTests/ResultConstructor.cs
tests/Ardalis.Result.UnitTests/ResultMap.cs
tests/Ardalis.Result.UnitTests/ResultVoidConstructor.cs
tests/Ardalis.Result.UnitTests/ResultVoidMap.cs
tests/Ardalis.Result.UnitTests/ResultVoidToResultOfT.cs

Add the ability to return an error body with the `Result.Conflict()` extension.

Add Result.Conflict

---

src/Ardalis.Result/Result.Void.cs
src/Ardalis.Result/Result.cs
tests/Ardalis.Result.UnitTests/ResultConstructor.cs
tests/Ardalis.Result.UnitTests/ResultVoidConstructor.cs
tests/Ardalis.Result.UnitTests/ResultVoidMap.cs
tests/Ardalis.Result.UnitTests/ResultVoidToResultOfT.cs

More often than not I find myself passing a single Validation error in the Result.Invalid method. This PR addresses that. 
I do believe this to be a needed improvement, as it's very annoying to create new Lists only to pass a single object in them.  
- Support for single validation error in the Result.Invalid method
- Added unit tests to validate behavior 
- All existing behavior remains the same. The single instance of the Validation Error will be passed in a new List<ValdiationError> upon Result.Invalid creation 
```
//This instantiates a new list with the single validation error in it
public new static Result Invalid(ValidationError validationError)
{
return new Result(ResultStatus.Invalid) { ValidationErrors = { validationError } };
}
```

Add support for single validation error with Result.Invalid

---

src/Ardalis.Result.AspNetCore/ResultStatusMap.cs
src/Ardalis.Result/Result.cs
src/Ardalis.Result/ResultExtensions.cs
src/Ardalis.Result/ResultStatus.cs

This is my take on adding the Critical Error status

Added CriticalError to ResultStatuses (#140)

---

src/Ardalis.Result.AspNetCore/MinimalApiResultExtensions.cs
src/Ardalis.Result/Result.Void.cs
tests/Ardalis.Result.UnitTests/ResultConstructor.cs
tests/Ardalis.Result.UnitTests/ResultMap.cs
tests/Ardalis.Result.UnitTests/ResultVoidConstructor.cs
tests/Ardalis.Result.UnitTests/ResultVoidMap.cs
tests/Ardalis.Result.UnitTests/ResultVoidToResultOfT.cs

* Adds missing CriticalError factory method to Result.Void
* Adds minimal api support for CriticalError
* Adds CriticalError unit tests

Adds missing Result.Void CriticalError method

---

src/Ardalis.Result.AspNetCore/MinimalApiResultExtensions.cs
src/Ardalis.Result.AspNetCore/ResultStatusMap.cs
src/Ardalis.Result/Result.Void.cs
src/Ardalis.Result/Result.cs
src/Ardalis.Result/ResultExtensions.cs
src/Ardalis.Result/ResultStatus.cs
tests/Ardalis.Result.AspNetCore.UnitTests/ResultConventionDefaultResultStatusMap.cs
tests/Ardalis.Result.AspNetCore.UnitTests/ResultConventionDefaultResultStatusMapModified.cs
tests/Ardalis.Result.UnitTests/PagedResultConstructor.cs
tests/Ardalis.Result.UnitTests/ResultConstructor.cs
tests/Ardalis.Result.UnitTests/ResultMap.cs
tests/Ardalis.Result.UnitTests/ResultVoidConstructor.cs
tests/Ardalis.Result.UnitTests/ResultVoidMap.cs
tests/Ardalis.Result.UnitTests/ResultVoidToResultOfT.cs

When making calls to downstream services or databases transient errors could occur that may get resolved if the operation is retried.
This PR adds an Unavailable result status and a mapping to a 503 Service Unavailable http result.
Usage scenarios:
1. A service adds a resiliency layer (using Polly for example) to handle retries.
instead of handling various exception or error types in the shared resiliency layer, the developer can handle these cases closer to where they occur and return Result.Unavailable. the resiliency layer can now be made generic, and error agnostic, and retry based on the result status.
2. while making a call to a downstream service, we get some transient error (database unavailable). the service layer can handle the error and return  Result.Unavailable and the result …

Add Unavailable result status

---

Directory.Packages.props
src/Ardalis.Result/Ardalis.Result.csproj
src/Ardalis.Result/Result.cs
tests/Ardalis.Result.UnitTests/SystemTextJsonSerializer.cs

Description of Changes: 
Fixes #91 
Fixes issue with lack of support for serialization of `Type` when using `System.Text.Json`'s serializer by removing the property from the exported json altogether. Unit tests show output of serialization for reference.
Pros:
- Fixes issue
- Makes Type an expression which simplifies Result's available API and reduces code (which appeared to be unused based on Samples, Docs, and Tests).
Cons:
- Adds additional but compatible dependency on `System.Text.Json` to core `Ardalis.Result` for .NET Standard users. This is already a "baked in" dependency in .NET 7 version.
https://www.nuget.org/packages/System.Text.Json/7.0.3#supportedframeworks-body-tab
Did you add tests? 
If no, why not? 
N/A

Fix Issue with Serializing Type When Using System.Text.Json

---

src/Ardalis.Result/Result.Void.cs
src/Ardalis.Result/Result.cs
src/Ardalis.Result/ValidationError.cs

Added an overload for the Invalid factory method of `Result` and `Result<T>` that accepts `params ValidationError[]`
Also adds 2 QOL constructors to the ValidationError class.
Closes #149

Add params overload for Invalid factory method

---

src/Ardalis.Result.AspNetCore/MinimalApiResultExtensions.cs
src/Ardalis.Result.AspNetCore/ResultStatusMap.cs

Stumbled upon this spelling mistake and figured I'd submit a MR to fix it.

occured -> occurred

---

src/Ardalis.Result/IResult.cs
src/Ardalis.Result/Result.Void.cs
src/Ardalis.Result/Result.cs
src/Ardalis.Result/ResultExtensions.cs
tests/Ardalis.Result.UnitTests/ErrorsAndValidationErrorsChanged.cs
tests/Ardalis.Result.UnitTests/PagedResultConstructor.cs

Auto-evaluate the Status property when Errors ou ValidationErrors are added to the result. 
**It only works when the result is created as Ok(), Error() ou Invalid()**.
The following unit test describes the functioning of this PR
```
[Fact]
public void ErrorAndValidationErrorChanged()
{
Result result = Result.Success(); // Created as Ok
result.IsSuccess.Should().Be(true);
result.Status.Should().Be(ResultStatus.Ok);
// Adding a validation error
result.ValidationErrors.Add(new ValidationError("Validation Error 1"));
result.IsSuccess.Should().Be(false);
result.Status.Should().Be(ResultStatus.Invalid); // <- Status changed to Invalid
// Adding an Error
result.Errors.Add("Error 1");
result.IsSuccess.Should().Be(false);
result.Status.Should().Be(ResultStatus.Error); // <- Status changed to Error …
```

closes #161 Auto-Evaluation of the Status property when Errors ou ValidationErrors are added to the result.

---

src/Ardalis.Result/ErrorList.cs
src/Ardalis.Result/Result.Void.cs
src/Ardalis.Result/Result.cs
src/Ardalis.Result/ResultExtensions.cs
tests/Ardalis.Result.UnitTests/PagedResultConstructor.cs
tests/Ardalis.Result.UnitTests/ResultConstructor.cs
tests/Ardalis.Result.UnitTests/ResultMap.cs
tests/Ardalis.Result.UnitTests/ResultVoidConstructor.cs
tests/Ardalis.Result.UnitTests/ResultVoidMap.cs
tests/Ardalis.Result.UnitTests/ResultVoidToResultOfT.cs

Update Error usage to utilize ErrorList record with ErrorMessages and CorrelationId

---

sample/Ardalis.Result.Sample.Core/Services/BadResultService.cs
sample/Ardalis.Result.Sample.Core/Services/WeatherServiceWithExceptions.cs
sample/Ardalis.Result.Sample.UnitTests/ServiceTests/BadResultService_ReturnResultWithError.cs
src/Ardalis.Result/Result.Void.cs
tests/Ardalis.Result.UnitTests/ResultImplicitOperators.cs

Fix Null Ref when returning Result.Error(string) non-generically.

---

src/Ardalis.Result.AspNetCore/MinimalApiResultExtensions.cs
tests/Ardalis.Result.AspNetCore.UnitTests/MinimalApiResultExtensionsCoverage.cs

Added an xUnit test to avoid future unhandled ResultStatus values
Fixes #191

Fix unhandled ResultStatus.NoContent in MinimalApiResultExtensions.ToMinimalApiResult

---

sample/Ardalis.Result.Sample.Core/Services/WeatherService.cs
src/Ardalis.Result.AspNetCore/ActionResultExtensions.cs
src/Ardalis.Result.AspNetCore/ResultConvention.cs
src/Ardalis.Result.AspNetCore/ResultStatusMap.cs
src/Ardalis.Result/IResult.cs
tests/Ardalis.Result.UnitTests/ResultConstructor.cs

Fixes #196
An assumption I made for setting the location header is that we could allow users to only define a relative location by deriving the base URL from the controller that is calling .ToActionResult on the Created result.
Is this OK or do you think we ought to allow them to specify the entire URL, or both?
Sorry If I've overlooked anything on this, it is my ~~first~~ second PR.
Old PR: #197

Add support for HttpStatusCode: Created to the ResultStatus mapping

---

src/Ardalis.Result/Result.Void.cs
src/Ardalis.Result/Result.cs

Added Result.Created methods to Result.Void static methods so that returned Result type is implicitly handled.
This allows for `return Result.Created(value);` and `return Result.Created(value, location);` to work effortlessly and as expected the same way that `Result.Success(value);` currently works.

Add Result.Created void methods so that return Result type is implicitly handled.

---

src/Ardalis.Result/ResultExtensions.cs
tests/Ardalis.Result.UnitTests/ResultBind.cs
tests/Ardalis.Result.UnitTests/ResultBindAsync.cs
tests/Ardalis.Result.UnitTests/ResultMap.cs
tests/Ardalis.Result.UnitTests/ResultMapAsync.cs
tests/Ardalis.Result.UnitTests/ResultVoidMapAsync.cs

This is related to https://github.com/ardalis/Result/issues/211
This is a PR that adds Bind in Addition to map to chain result producing functions. It also has overloads for async for all void result and task result types so no conversions should be needed.

Add Bind in addition to Map to support Railway Oriented Programming

---

src/Ardalis.Result/ResultExtensions.cs
tests/Ardalis.Result.UnitTests/ResultGenericToVoidMap.cs

See https://github.com/ardalis/Result/issues/212

Add Map Extension Method to Support Mapping from Result<T> to Result

---

src/Ardalis.Result/ValidationError.cs

Related to https://github.com/ardalis/Result/issues/208
I've opted not to refactor other areas of the code base this could be applied to as both forms are valid.

Add identifier & error message constructor to ValidationError
